server:
  port: 8080

spring:
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379
  application:
    name: bank-api
  data:
    mongodb:
      database: atm_data_db
      port: 27017
      host: localhost

redis:
  timeout: 2000
  cache-timeout: 1

bank-api:
  information:
    host: localhost


