server:
  port: 8080

spring:
  cloud:
    aws:
      sqs:
        endpoint: http://localhost:4566
        region: eu-central-1
  cache:
    type: redis
  application:
    name: bank-api
  data:
    mongodb:
      database: atm_data_db
      port: 27017
      host: localhost
    redis:
      host: localhost
      port: 6379

redis:
  timeout: 2000
  cache-timeout: 1

bank-api:
  apis:
    base-path: /api/v2
    find-banks-path: /banks

  sqs:
    queue:
      name: send-eventhub
  information:
    host: localhost


