server:
  port: 8080

spring:
  cloud:
    aws:
      sqs:
        endpoint: http://localhost:4566
        region: eu-central-1
  cache:
    type: redis
  application:
    name: bank-api
  data:
    mongodb:
      database: atm_data_db
      host: localhost
      port: 27017
      password: password
    redis:
      cluster:
        nodes: http://localhost:6379
      password: password

bank-api:
  apis:
    base-path: /api/v2
    find-banks-path: /banks
    info-path: /info

  sqs:
    queue:
      name: send-eventhub
  information:
    host: localhost


