version: "3.9"
services:
  bank-api:
    image: manuelrojas19/bank-api
    restart: always
    ports:
      - "8081:8080"
    environment:
      spring.data.mongodb.host: mongo
    networks:
      - techbanknet
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - "mongo_data:/data/db"
    networks:
      - techbanknet
  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - techbanknet
  aws-local:
    image: localstack/localstack:1.3
    ports:
      - "4566:4566"
      - "8283:8080"
    environment:
      - "SERVICES=sqs,sns"
    volumes:
      - "./localstack_bootstrap:/docker-entrypoint-initaws.d/"
    networks:
      - techbanknet

volumes:
  redis_data:
    driver: local
  mongo_data:
    driver: local

networks:
  techbanknet: