version: "3.9"
services:
  bank-api:
    image: manuelrojas19/bank-api
    restart: always
    ports:
      - "8081:8080"
    environment:
      spring.data.mongodb.host: mongo
      spring.data.redis.cluster.nodes: redis-single-node-cluster:6379
      spring.cloud.aws.sqs.endpoint: http://aws-local:4566
      AWS_REGION: eu-central-1
      AWS_ACCESS_KEY_ID: id
      AWS_SECRET_ACCESS_KEY: key
    networks:
      - bank-api-network
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - "mongo_data:/data/db"
      - "./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d/:ro"
    networks:
      - bank-api-network
  aws-local:
    image: localstack/localstack:1.3
    ports:
      - "4566:4566"
      - "8283:8080"
    environment:
      - "SERVICES=sqs,sns"
    volumes:
      - "./docker-entrypoint-initaws.d:/docker-entrypoint-initaws.d/"
    networks:
      - bank-api-network
  redis-single-node-cluster:
    image: bitnami/redis-cluster
    environment:
      - 'ALLOW_EMPTY_PASSWORD=yes'
      - 'REDIS_CLUSTER_REPLICAS=0'
      - 'REDIS_NODES=127.0.0.1 127.0.0.1 127.0.0.1'
      - 'REDIS_CLUSTER_CREATOR=yes'
      - 'REDIS_CLUSTER_DYNAMIC_IPS=no'
      - 'REDIS_CLUSTER_ANNOUNCE_IP=127.0.0.1'
    ports:
      - '6379:6379'
    networks:
      - bank-api-network

volumes:
  mongo_data:
    driver: local

networks:
  bank-api-network: